<!-- Paste this code into an external JavaScript file named: quiz_config.js  -->

/* This script and many more are available free online at
The JavaScript Source :: http://www.javascriptsource.com
Created by: James Crooke :: http://www.cj-design.com */

var questions = new Array();
var choices = new Array();
var answers = new Array();
var response = new Array();
var feedback = new Array();

// To add more questions, just follow the format below.

questions[0] = "In the symmetric cryptosystem if Oscar gets a hold of the same decryption box $d()$ that Bob has then he is successful in evesdropping Alice and Bob's private messages";
choices[0] = new Array();
choices[0][0] = "true";
choices[0][1] = "false";
answers[0] = choices[0][1];
feedback[0] = "Correct. Even if Oscar has access to d() he cannot decrypt the messages without the key";

questions[1] = "The keys generated by the key generator can be communicated to Alice and Bob using the Cloud";
choices[1] = new Array();
choices[1][0] = "true";
choices[1][1] = "false";
answers[1] = choices[1][1];
feedback[1] = "Correct. The keys should only be communicated using a secure channel";

questions[2] = "The Shannon's maxim postulates that that the cryptographic algorithm should remain a secret because security can be achieved through obsecurity ";
choices[2] = new Array();
choices[2][0] = "true";
choices[2][1] = "false";
answers[2] = choices[2][1];
feedback[2] = "Correct. Shannon's maxim postulates that a cryptosystem should be designed with the assumption in mind that the <b>algorithm</b> will be compromised.";

questions[3] = "Cryptanalysis is a field particular to hackers";
choices[3] = new Array();
choices[3][0] = "true";
choices[3][1] = "false";
answers[3] = choices[3][1];
feedback[3] = "Correct. Cryptanalysis is no longer associated with hackers alone but is now a scientific discipline involving cryptanalysts as well as academic researchers.";